import Link from "next/link";
import { ClipboardList, LayoutDashboard, LogOut, Package, ShoppingBag, Users } from "lucide-react";
import { formatRupiah } from "@/lib/mock-data";

const orders = [
  ["RK-261002-017","Nadia Putri","Roti Sobek Cokelat","03 Okt 2026","Diproses","32000"],
  ["RK-261002-016","Dimas Akbar","Chocolate Fudge Cake","04 Okt 2026","Menunggu","145000"],
  ["RK-261002-015","Siti Rahma","Croissant Butter × 4","03 Okt 2026","Siap diambil","72000"],
  ["RK-261002-014","Fajar Nugraha","Bolu Pandan Keju","03 Okt 2026","Diproses","55000"],
];

export default function AdminPage() {
  return <main className="admin-layout"><aside className="sidebar"><Link className="brand" href="/"><span className="brand-mark">RK</span><span>RotiKita</span></Link><nav className="side-nav"><a className="side-link active"><LayoutDashboard size={19}/><span>Ringkasan</span></a><a className="side-link"><ClipboardList size={19}/><span>Pesanan</span></a><a className="side-link"><Package size={19}/><span>Produk</span></a><a className="side-link"><Users size={19}/><span>Pelanggan</span></a><Link className="side-link" href="/"><LogOut size={19}/><span>Keluar</span></Link></nav></aside><section className="admin-main"><div className="admin-top"><div><h1>Ringkasan produksi</h1><p>Kamis, 2 Oktober 2026 · pantau pesanan dan kapasitas harian.</p></div><button className="primary-btn">Tambah produk</button></div><div className="stats"><div className="stat"><span className="stat-label">Pesanan hari ini</span><strong>18</strong><small>+4 dari kemarin</small></div><div className="stat"><span className="stat-label">Perlu dikonfirmasi</span><strong>5</strong><small style={{color:"#a46221"}}>Periksa pembayaran</small></div><div className="stat"><span className="stat-label">Sedang diproduksi</span><strong>9</strong><small>Sesuai jadwal</small></div><div className="stat"><span className="stat-label">Pendapatan</span><strong style={{fontSize:"1.55rem"}}>{formatRupiah(1745000)}</strong><small>Hari ini</small></div></div><div className="capacity"><section className="panel"><div className="panel-head"><h2>Kapasitas produksi</h2><span className="tag">3 Oktober</span></div>{[["Roti",42,60],["Kue",12,20],["Pastry",31,40]].map(([name,used,max])=><div className="progress-row" key={name as string}><div className="progress-label"><strong>{name}</strong><span>{used}/{max} produk</span></div><div className="progress"><span style={{width:`${Number(used)/Number(max)*100}%`}}/></div></div>)}</section><section className="panel"><div className="panel-head"><h2>Catatan hari ini</h2><ShoppingBag size={20}/></div><p style={{color:"var(--muted)",lineHeight:1.7}}>Pesanan croissant hampir mencapai kuota. Tutup pre-order otomatis setelah sisa 9 produk terpenuhi.</p><button className="secondary-btn" style={{marginTop:20}}>Atur kapasitas</button></section></div><section className="panel"><div className="panel-head"><h2>Pesanan terbaru</h2><button className="secondary-btn">Lihat semua</button></div><div className="table-wrap"><table><thead><tr><th>No. pesanan</th><th>Pelanggan</th><th>Produk</th><th>Jadwal</th><th>Status</th><th>Total</th></tr></thead><tbody>{orders.map((o)=><tr key={o[0]}><td><strong>{o[0]}</strong></td><td>{o[1]}</td><td>{o[2]}</td><td>{o[3]}</td><td><span className={`status-badge ${o[4]==="Menunggu"?"status-wait":o[4]==="Siap diambil"?"status-ready":"status-process"}`}>{o[4]}</span></td><td>{formatRupiah(Number(o[5]))}</td></tr>)}</tbody></table></div></section></section></main>;
}
